### ISSUE TITLE
Сделать все поля формы обязательными)

### ISSUE THREAD

**Issue by igosheva** [shushper/Burgers#10]
https://github.com/shushper/Burgers/blob/0c55c6e4e08516fddf14e115a63baf44385dbc50/index.html#L387

**Comment by igosheva** [comment]
Кроме поля комментария

**Comment by shushper** [comment]
Может стоит корпус и этаж оставить необязательными?

**Comment by shushper** [comment]
Корпус и этаж оставил необязательными
